config/routes.rb
Rails.application.routes.draw do


  resources :services
  resources :promos
  devise_for :bussinesses, controllers: {
  sessions: 'bussiness/sessions',
  registrations: 'bussiness/registrations'
  }

  authenticated :bussiness do
    root 'orders#index', as: :bussiness_root
  end

  resources :stores
  root to: "pages#home"
  get "pages/show", page:'family', as: 'family'
  get "pages/administrate_user", as: 'activation'
  
  resources :resolutions, only: [:index, :update, :destroy]
  resources :answers
  resources :stores
  resources :products
  resources :cart, only: [:show]
  resources :orders, only: [:index, :update]
  resources :order_items, only: [:create, :update, :destroy]
  resources :order_statuses

  get "orders/report", as: "report"

  resources :decisions
  resources :children
  resources :chats
  resources :workers
  resources :common_areas
  resources :newsletters
  resources :advertisements
  resources :complaints
  resources :vehicles
  resources :pets
  resources :apartments
  resources :werehouses

  namespace :admin do
    resources :users
    resources :advertisements
    resources :apartments
    resources :common_areas
    resources :complaints
    resources :newsletters
    resources :pets
    resources :vehicles
    resources :werehouses
    resources :workers
    resources :decisions
    resources :hobbies
    resources :products
    resources :order_statuses
    resources :orders
    root to: "users#index"
  end

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }

  resources :decisions do 
    member do
      put "like", to: "decisions#upvote"
      put "dislike", to: "decisions#downvote"
    end
  end

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :apartments
      resources :advertisements
      resources :common_areas
      resources :complaints
      resources :orders
    end
  end

  resources :users, only: [:index, :update, :destroy]

  mount ActionCable.server => "/cable"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :werehouse, optional: true
  has_many :users
  has_many :children
  has_many :complaints
  has_many :pets
  has_many :vehicles
  has_many :werehouses
  has_many :orders

  def apto
  	apto = "#{number}-""#{block}"
  end
end

app/models/bussiness.rb
class Bussiness < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_one :store
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :apartment
end

app/models/common_area.rb
class CommonArea < ApplicationRecord
  belongs_to :user
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :apartment, foreign_key: 'apartment_id'

  mount_uploader :imagen, FotoUploader
end

app/models/decision.rb
class Decision < ApplicationRecord
	acts_as_votable
end

app/models/hobby.rb
class Hobby < ApplicationRecord
	# has_many :user_hobbies,  dependent: :destroy
	has_many :users
	# , through: :user_hobbies
	has_many :promos
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
	mount_uploader :file, FotoUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :bussiness
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status, on: :create

  before_save :update_total
  

  def total
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private
  def set_order_status
    self.order_status_id = 1
  end

  def update_total
    self[:total] = total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def product_name
    product.name
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :apartment
end

app/models/product.rb
class Product < ApplicationRecord
mount_uploader :image, FotoUploader
	has_many :order_items
	belongs_to :store

  default_scope { where(active: true) }
end

app/models/promo.rb
class Promo < ApplicationRecord
  belongs_to :hobby

  mount_uploader :image, FotoUploader
end

app/models/service.rb
class Service < ApplicationRecord
	mount_uploader :photo, FotoUploader
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :bussiness
  has_many :products

  mount_uploader :image, FotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

before_create -> {self.token = generate_token}
#relaciones
  belongs_to :apartment
  # has_many :user_hobbies
  has_many :hobbies
  # , through: :user_hobbies
  has_many :chats
  has_many :orders
  

  #validacion de registro
  validates :email, :name, :last_name, :gender, :cellphone, :day_of_birth, :apartment_id, presence: true 
  validates :cellphone, numericality: true
  validates :cellphone, length: {is: 10}
  

  private
 
  def generate_token
      loop do
        token = SecureRandom.hex
        return token unless User.exists?({token: token})
      end
  end
  
end

app/models/user_hobby.rb
class UserHobby < ApplicationRecord
  belongs_to :user
  belongs_to :hobby
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :apartment
  #validates :plate, format: {with: "^[a-zA-Z]{3}\\d{3}$"}
  #validates :plate, format: {with: "^[a-zA-Z]{3}\\d{2}[a-zA-Z]{1}$"}
end

app/models/werehouse.rb
class Werehouse < ApplicationRecord
  belongs_to :apartment
end

app/models/worker.rb
class Worker < ApplicationRecord
	mount_uploader :imagen, FotoUploader
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:  [:index]
  before_action :authenticate_bussiness!, only: [:new, :create]
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
    @products = Product.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Store was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :image, :bussiness_id)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :store_name %>
  </div>

  <div class="field">
    <%= form.label :image, t('Imagen') %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.hidden_field :bussiness_id, id: :store_user_id, value: current_bussiness.id %>
  </div>

  <div class="actions">
      <%= image_submit_tag("btn-crear.png") %>
    </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
  <h1>Tiendas para ti</h1>
  <div class="container-welcome">
	  <% @stores.each do |store| %>
	    <%= link_to store_path(store) do %>
	      <%= image_tag(store.image_url, :width => 150, :height => 150) if store.image.present? %>
	      <hr class="line">
	    <%end %>
	  <% end %>  	
  </div>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<div class="row">
	<%= image_tag(@store.image_url, :width => 300, :height => 200) if @store.image.present? %>
</div>

<div class="row">
  <% @store.products.each do |product| %>
  <div class="col-md-2">
    <span class="thumbnail">
        <%= image_tag(product.image.url, alt: 'Image', class: "product-image", style: "width: 100px; height: 100px;") if product.image? %>
        <h4 class= "product_name"><%= product.name %></h4>
        <hr class="line">
        <div class="row">
          <div class="col-md-12">
            <p class="sell_price"><%= number_to_currency(product.price, strip_insignificant_zeros: true)  %></p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <%= form_for :order_item, url: order_items_path, remote: true do |f| %>
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.hidden_field :quantity, value: 1, class: "form input_product", min: 1 %>
          </div>
        </div>
        
        <div class="row">
          <div class="col-md-12">
            <%= f.button style: style="width: 50px;height: 40px;padding:0px;display: block;margin: 3px auto; border: none; color: #38133a; background: none;" do %>
              pedir
            <%end %>
          </div>
          <%end %>
        </div>
    </span>
  </div>
  <%end%>
</div>
       