config/routes.rb
Rails.application.routes.draw do


  resources :services
  resources :promos
  devise_for :bussinesses, controllers: {
  sessions: 'bussiness/sessions',
  registrations: 'bussiness/registrations'
  }

  authenticated :bussiness do
    root 'orders#index', as: :bussiness_root
  end

  resources :stores
  root to: "pages#home"
  get "pages/show", page:'family', as: 'family'
  get "pages/administrate_user", as: 'activation'
  
  resources :resolutions, only: [:index, :update, :destroy]
  resources :answers
  resources :stores
  resources :products
  resources :cart, only: [:show]
  resources :orders, only: [:index, :update]
  resources :order_items, only: [:create, :update, :destroy]
  resources :order_statuses

  get "orders/report", as: "report"

  resources :decisions
  resources :children
  resources :chats
  resources :workers
  resources :common_areas
  resources :newsletters
  resources :advertisements
  resources :complaints
  resources :vehicles
  resources :pets
  resources :apartments
  resources :werehouses

  namespace :admin do
    resources :users
    resources :advertisements
    resources :apartments
    resources :common_areas
    resources :complaints
    resources :newsletters
    resources :pets
    resources :vehicles
    resources :werehouses
    resources :workers
    resources :decisions
    resources :hobbies
    resources :products
    resources :order_statuses
    resources :orders
    root to: "users#index"
  end

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }

  resources :decisions do 
    member do
      put "like", to: "decisions#upvote"
      put "dislike", to: "decisions#downvote"
    end
  end

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :apartments
      resources :advertisements
      resources :common_areas
      resources :complaints
      resources :orders
    end
  end

  resources :users, only: [:index, :update, :destroy]

  mount ActionCable.server => "/cable"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/common_area.rb
class CommonArea < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/common_areas_controller.rb
module Admin
  class CommonAreasController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = CommonArea.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   CommonArea.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/v1/common_areas_controller.rb
class Api::V1::CommonAreasController < ApplicationController

  def index
    @common_areas = CommonArea.all
  end

      def create
    @common_area = CommonArea.new(common_area_params)
    if @common_area.save
      render json: common_area, status: 201, location: [:api, common_area]
    else
      render json: { errors: common_area.errors }, status: 422
    end
	end

private

	def common_area_params
	  params.require(:common_area).permit(:title, :date, :start_hour, :end_hour, :user_id)
	end
  
end

app/controllers/common_areas_controller.rb
class CommonAreasController < ApplicationController
  before_action :set_common_area, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /common_areas
  # GET /common_areas.json
  def index
    @common_areas = CommonArea.all
  end

  # GET /common_areas/1
  # GET /common_areas/1.json
  def show
  end

  # GET /common_areas/new
  def new
    @common_area = CommonArea.new
  end

  # GET /common_areas/1/edit
  def edit
  end

  # POST /common_areas
  # POST /common_areas.json
  def create
    @common_area = CommonArea.new(common_area_params)

    respond_to do |format|
      if @common_area.save
        format.html { redirect_to @common_area, notice: 'Common area was successfully created.' }
        format.json { render :show, status: :created, location: @common_area }
      else
        format.html { render :new }
        format.json { render json: @common_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /common_areas/1
  # PATCH/PUT /common_areas/1.json
  def update
    respond_to do |format|
      if @common_area.update(common_area_params)
        format.html { redirect_to @common_area, notice: 'Common area was successfully updated.' }
        format.json { render :show, status: :ok, location: @common_area }
      else
        format.html { render :edit }
        format.json { render json: @common_area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /common_areas/1
  # DELETE /common_areas/1.json
  def destroy
    @common_area.destroy
    respond_to do |format|
      format.html { redirect_to common_areas_url, notice: 'Common area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_common_area
      @common_area = CommonArea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def common_area_params
      params.require(:common_area).permit(:title, :date, :start_hour, :end_hour, :user_id, :aproved)
    end
end

app/helpers/common_areas_helper.rb
module CommonAreasHelper
end

app/views/common_areas/_form.html.erb
<%= form_with(model: common_area, local: true) do |form| %>
  <% if common_area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(common_area.errors.count, "error") %> prohibited this common_area from being saved:</h2>

      <ul>
      <% common_area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, t('Lugar') %>
    <%= form.text_field :title, id: :common_area_place, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :date, t('Fecha') %>
    <%= form.date_select :date, id: :common_area_date %>
  </div>

  <div class="field">
    <%= form.label :start_hour, t('Hora de inicio') %>
    <%= form.time_select :start_hour, id: :common_area_start_hour %>
  </div>

  <div class="field">
    <%= form.label :end_hour, t('Hora de cierre') %>
    <%= form.time_select :end_hour, id: :common_area_end_hour %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

    <div class="field">
    <%= form.hidden_field :aproved, value: false %>
  </div>

  <div class="actions">
    <%= image_submit_tag("btn-enviar.png") %>
  </div>
<% end %>

app/views/common_areas/edit.html.erb
<h1>Editar solicitud de áreas comunes</h1>

<%= render 'form', common_area: @common_area %>

<%= link_to 'Mostrar', @common_area %> |
<%= link_to 'Regresar', common_areas_path %>

app/views/common_areas/index.html.erb
<div class="row">
  <div class="col-md-6">
  <h1>Áreas comunes</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Lugar</th>
        <th>Fecha</th>
        <th>Incio</th>
        <th>Final</th>
        <th>Usuario</th>
        <th>Aprobado?</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @common_areas.each do |common_area| %>
        <tr>
          <td><%= common_area.title %></td>
          <td><%= common_area.date %></td>
          <td><%= common_area.start_hour.hour %>:<%= common_area.start_hour.min %></td>
          <td><%= common_area.end_hour.hour %>:<%= common_area.end_hour.min %></td>
          <td><%= common_area.user.name %> <%= common_area.user.last_name %></td>
          <%if common_area.aproved?%> 
            <td><i class="fa fa-check" aria-hidden="true"></i></td>
          <%else %>
            <td> pendiente </td>
          <%end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to new_common_area_path do%>
    <%= image_tag('solicitud.png') %>
  <%end %>
  </div>
  <div class="col-md-6">
    <div id="calendar"></div>
  </div>
</div>
<div class="row">
  <div class="col-md-6">
    <div class="help-box">
        
        <h2><strong>NOTA:</strong></h2>
        <%= image_tag('close.png', class: "close") %>
        <p>En este espacio puede hacer solicitudes de los espacio comunes que tenemos a disposición. Cree la solicitud y tan pronto la solicitud sea aprobada por la administración se verá en la tabla.</p>
    </div>
  </div>
</div>

app/views/common_areas/new.html.erb
<h1>Solicitud de áreas comunes</h1>

<%= render 'form', common_area: @common_area %>

<%= link_to 'Regresar', common_areas_path %>

app/views/common_areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lugar:</strong>
  <%= @common_area.title %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @common_area.date %>
</p>

<p>
  <strong>Hora de inicio:</strong>
  <%= @common_area.start_hour.hour %>:<%= @common_area.start_hour.min %>
</p>

<p>
  <strong>Hora final:</strong>
  <%= @common_area.end_hour.hour %>:<%= @common_area.end_hour.min %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @common_area.user.name %> <%= @common_area.user.last_name %>
</p>

<%= link_to 'Editar', edit_common_area_path(@common_area) %> |
<%= link_to 'Regresar', common_areas_path %>