config/routes.rb
Rails.application.routes.draw do


  resources :services
  resources :promos
  devise_for :bussinesses, controllers: {
  sessions: 'bussiness/sessions',
  registrations: 'bussiness/registrations'
  }

  authenticated :bussiness do
    root 'orders#index', as: :bussiness_root
  end

  resources :stores
  root to: "pages#home"
  get "pages/show", page:'family', as: 'family'
  get "pages/administrate_user", as: 'activation'
  
  resources :resolutions, only: [:index, :update, :destroy]
  resources :answers
  resources :stores
  resources :products
  resources :cart, only: [:show]
  resources :orders, only: [:index, :update]
  resources :order_items, only: [:create, :update, :destroy]
  resources :order_statuses

  get "orders/report", as: "report"

  resources :decisions
  resources :children
  resources :chats
  resources :workers
  resources :common_areas
  resources :newsletters
  resources :advertisements
  resources :complaints
  resources :vehicles
  resources :pets
  resources :apartments
  resources :werehouses

  namespace :admin do
    resources :users
    resources :advertisements
    resources :apartments
    resources :common_areas
    resources :complaints
    resources :newsletters
    resources :pets
    resources :vehicles
    resources :werehouses
    resources :workers
    resources :decisions
    resources :hobbies
    resources :products
    resources :order_statuses
    resources :orders
    root to: "users#index"
  end

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }

  resources :decisions do 
    member do
      put "like", to: "decisions#upvote"
      put "dislike", to: "decisions#downvote"
    end
  end

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :apartments
      resources :advertisements
      resources :common_areas
      resources :complaints
      resources :orders
    end
  end

  resources :users, only: [:index, :update, :destroy]

  mount ActionCable.server => "/cable"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :werehouse, optional: true
  has_many :users
  has_many :children
  has_many :complaints
  has_many :pets
  has_many :vehicles
  has_many :werehouses
  has_many :orders

  def apto
  	apto = "#{number}-""#{block}"
  end
end

app/models/bussiness.rb
class Bussiness < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_one :store
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
end

app/models/child.rb
class Child < ApplicationRecord
  belongs_to :apartment
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :apartment, foreign_key: 'apartment_id'

  mount_uploader :imagen, FotoUploader
end

app/models/decision.rb
class Decision < ApplicationRecord
	acts_as_votable
end

app/models/hobby.rb
class Hobby < ApplicationRecord
	# has_many :user_hobbies,  dependent: :destroy
	has_many :users
	# , through: :user_hobbies
	has_many :promos
end

app/models/newsletter.rb
class Newsletter < ApplicationRecord
	mount_uploader :file, FotoUploader
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :bussiness
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status, on: :create

  before_save :update_total
  

  def total
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private
  def set_order_status
    self.order_status_id = 1
  end

  def update_total
    self[:total] = total
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def product_name
    product.name
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :apartment
end

app/models/product.rb
class Product < ApplicationRecord
mount_uploader :image, FotoUploader
	has_many :order_items
	belongs_to :store

  default_scope { where(active: true) }
end

app/models/promo.rb
class Promo < ApplicationRecord
  belongs_to :hobby

  mount_uploader :image, FotoUploader
end

app/models/service.rb
class Service < ApplicationRecord
	mount_uploader :photo, FotoUploader
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :bussiness
  has_many :products

  mount_uploader :image, FotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

before_create -> {self.token = generate_token}
#relaciones
  belongs_to :apartment
  # has_many :user_hobbies
  has_many :hobbies
  # , through: :user_hobbies
  has_many :chats
  has_many :orders
  

  #validacion de registro
  validates :email, :name, :last_name, :gender, :cellphone, :day_of_birth, :apartment_id, presence: true 
  validates :cellphone, numericality: true
  validates :cellphone, length: {is: 10}
  

  private
 
  def generate_token
      loop do
        token = SecureRandom.hex
        return token unless User.exists?({token: token})
      end
  end
  
end

app/models/user_hobby.rb
class UserHobby < ApplicationRecord
  belongs_to :user
  belongs_to :hobby
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :apartment
  #validates :plate, format: {with: "^[a-zA-Z]{3}\\d{3}$"}
  #validates :plate, format: {with: "^[a-zA-Z]{3}\\d{2}[a-zA-Z]{1}$"}
end

app/models/werehouse.rb
class Werehouse < ApplicationRecord
  belongs_to :apartment
end

app/models/worker.rb
class Worker < ApplicationRecord
	mount_uploader :imagen, FotoUploader
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_complaint, only: [:show, :edit, :update, :destroy]

  def index
    @complaints = Complaint.all
  end

  def edit
  end

  def show
  end

  def update
    @complaint = Complaint.find(params[:id])
    @complaint.update!(answer_params)
    redirect_to answers_path
  end

  def destroy
    @complaint = Complaint.find(params[:id])
    @complaint.destroy
    redirect_to answers_path
  end

  private

    def set_complaint
      @complaint = Complaint.find(params[:id])
    end
  def answer_params
      params.require(:complaint).permit(:category, :description, :answer, :solved,:topic, :imagen, :apartment_id)
    end
end

app/views/answers/edit.html.erb
<h1>Editar queja o reclamo</h1>

<div class="col-md-6">
  <%= form_with(model: @complaint, url: answer_path(@complaint), local: true) do |form| %>
    <div class="field">
      <%= form.hidden_field :category %>
    </div>

    <div class="field">
      <%= form.hidden_field :topic%>
    </div>

    <div class="field">
      <%= form.hidden_field :description, id: :complaint_description, class:"form-control ggg" %>
    </div>

    <div class="field">
      <%= form.hidden_field :imagen %>
    </div>

    <div class="field">
      <%= form.label :answer, t('Respuesta') %>
      <%= form.text_area :answer, id: :complaint_answer, class:"form-control ggg" %>
    </div>

    <div class="field">
      <%= form.label :solved, t('¿La solicitud a sido resuelta?')%>
      <%= form.check_box :solved, class: "checkbox"%>
    </div>

    <div class="field">
      <%= form.hidden_field :apartment_id, value: current_user.apartment.id %>
    </div>

    <div class="actions">
      <%= image_submit_tag("btn-enviar.png") %>
    </div>
  <% end %>
</div>


<%= link_to 'Regresar', answers_path %>

app/views/answers/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h1>Atender Quejas y Reclamos</h1>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="card">
        <%@complaints.each do |answer| %>
        <div class="row">
          <div class="col-md-6">
            <div class="preview-pic">
              <%= image_tag(answer.imagen_url, :width => 200, :height => 200) if answer.imagen.present? %>
            </div>
          </div>
          <div class="col-md-6">
            <%if answer.solved %>
            <h3 class="product-title"> <span class="fa fa-check"></span></h3>
            <%else %>
            <h3 class="product-title">pendiente</h3>
            <%end %>
            <h3 class="product-title">Apartamento: <%= answer.apartment.apto %></h3>
            <h4 class="product-info">Categoría:<%= answer.category %></h4>
            <h4 class="product-info">Asunto:<%= answer.topic %></h4>
            <p class="product-description">Descripción:<%= answer.description %></p>
            <p class="product-description">Respuesta:<%= answer.answer %></p>
            <%= link_to "responder", edit_answer_path(answer)  %>
          </div>
        </div>
        <%end %>
    </div>

<div class="col-md-6">
</div>

app/views/answers/show.html.erb
<p>
  <strong>Tipo:</strong>
  <%= @complaint.category %>
</p>

<p>
  <strong>Asunto:</strong>
  <%= @complaint.topic %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @complaint.description %>
</p>

<p>
  <strong>Respuesta:</strong>
  <%= @complaint.answer %>
</p>

<p>
  <strong>Resuelto?:</strong>
  <%= @complaint.solved %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@complaint.imagen_url, :width => 600, :height => 600) if @complaint.imagen.present? %>
</p>

<p>
  <strong>Apartmento:</strong>
  <%= @complaint.apartment.apto %>
</p>

<%= link_to 'Editar', edit_complaint_path(@complaint) %> |
<%= link_to 'Regresar', complaints_path %>