config/routes.rb
Rails.application.routes.draw do


  resources :services
  resources :promos
  devise_for :bussinesses, controllers: {
  sessions: 'bussiness/sessions',
  registrations: 'bussiness/registrations'
  }

  authenticated :bussiness do
    root 'orders#index', as: :bussiness_root
  end

  resources :stores
  root to: "pages#home"
  get "pages/show", page:'family', as: 'family'
  get "pages/administrate_user", as: 'activation'
  
  resources :resolutions, only: [:index, :update, :destroy]
  resources :answers
  resources :stores
  resources :products
  resources :cart, only: [:show]
  resources :orders, only: [:index, :update]
  resources :order_items, only: [:create, :update, :destroy]
  resources :order_statuses

  get "orders/report", as: "report"

  resources :decisions
  resources :children
  resources :chats
  resources :workers
  resources :common_areas
  resources :newsletters
  resources :advertisements
  resources :complaints
  resources :vehicles
  resources :pets
  resources :apartments
  resources :werehouses

  namespace :admin do
    resources :users
    resources :advertisements
    resources :apartments
    resources :common_areas
    resources :complaints
    resources :newsletters
    resources :pets
    resources :vehicles
    resources :werehouses
    resources :workers
    resources :decisions
    resources :hobbies
    resources :products
    resources :order_statuses
    resources :orders
    root to: "users#index"
  end

  devise_for :users, controllers: {
  sessions: 'users/sessions',
  registrations: 'users/registrations'
  }

  resources :decisions do 
    member do
      put "like", to: "decisions#upvote"
      put "dislike", to: "decisions#downvote"
    end
  end

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      resources :apartments
      resources :advertisements
      resources :common_areas
      resources :complaints
      resources :orders
    end
  end

  resources :users, only: [:index, :update, :destroy]

  mount ActionCable.server => "/cable"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :werehouse, optional: true
  has_many :users
  has_many :children
  has_many :complaints
  has_many :pets
  has_many :vehicles
  has_many :werehouses
  has_many :orders

  def apto
  	apto = "#{number}-""#{block}"
  end
end

app/controllers/admin/apartments_controller.rb
module Admin
  class ApartmentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Apartment.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Apartment.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:number, :block, :parking_lots, :bikes_parking, :area, :werehouse_id)
    end
end

app/controllers/api/v1/Apartments_controller.rb
class Api::V1::ApartmentsController < ApplicationController

  def index
    @apartments = Apartment.all
  end
  
  def create
    @apartment = Apartment.new(apartment_params)
    if @apartment.save
      render json: apartment, status: 201, location: [:api, apartment]
    else
      render json: { errors: apartment.errors }, status: 422
    end
	end

private

	def apartment_params
	  params.require(:apartment).permit(:number, :block, :parking_lots, :bikes_parking, :storage, :coefficient)
	end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, local: true) do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
      <% apartment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number, t('Número') %>
    <%= form.text_field :number, id: :apartment_number, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :block, t('Bloque') %>
    <%= form.text_field :block, id: :apartment_block, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :parking_lots, t('Parqueadero') %>
    <%= form.text_field :parking_lots, id: :apartment_parking_lots, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :bikes_parking, t('Parqueadero de Bicicleta') %>
    <%= form.text_field :bikes_parking, id: :apartment_bikes_parking, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :area, t('Área') %>
    <%= form.text_field :area, id: :apartment_area, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :werehouse_id %>
    <%= form.text_field :werehouse_id, id: :apartment_werehouse_id %>
  </div>

  <div class="actions">
    <%= form.submit 'Crear apartamento', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<h1>Editar Apartamento</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Mostrar', @apartment %> |
<%= link_to 'Regresar', apartments_path %>

app/views/apartments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Apartamentos</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Block</th>
      <th>Parking lots</th>
      <th>Bikes parking</th>
      <th>Area</th>
      <th>Werehouse</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apartments.each do |apartment| %>
      <tr>
        <td><%= apartment.number %></td>
        <td><%= apartment.block %></td>
        <td><%= apartment.parking_lots %></td>
        <td><%= apartment.bikes_parking %></td>
        <td><%= apartment.area %></td>
        <td><%= apartment.werehouse %></td>
        <td><%= link_to 'Mostrar', apartment %></td>
        <td><%= link_to 'Editar', edit_apartment_path(apartment) %></td>
        <td><%= link_to 'Borrar', apartment, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Crear un apartamento', new_apartment_path %>

app/views/apartments/new.html.erb
<h1>Crear nuevo apartamento</h1>

<%= render 'form', apartment: @apartment %>

<%= link_to 'Regresar', apartments_path %>

app/views/apartments/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Número:</strong>
  <%= @apartment.number %>
</p>

<p>
  <strong>Bloque:</strong>
  <%= @apartment.block %>
</p>

<p>
  <strong>Parqueadero:</strong>
  <%= @apartment.parking_lots %>
</p>

<p>
  <strong>Parqueadero de Bicicletas:</strong>
  <%= @apartment.bikes_parking %>
</p>

<p>
  <strong>Área:</strong>
  <%= @apartment.area %>
</p>

<%if @apartment.werehouse %>
<p>
  <strong>Empleada:</strong>
  <%= @apartment.werehouse.name %> <%= @apartment.werehouse.last_name %>
</p>
<%end %>

<%= link_to 'Editar', edit_apartment_path(@apartment) %> |
<%= link_to 'Regresar', apartments_path %>